# GitHub Sponsors - Support BAZINGA development
github: [bitsabhi]

# Crypto - ETH/EVM Compatible (Ethereum, Polygon, Arbitrum, Base, etc.)
custom: [
  'https://etherscan.io/address/0x720ceF54bED86C570837a9a9C69F1Beac8ab8C08',
  'https://zenodo.org/records/18607789'
]
