# GitHub Sponsors - Support BAZINGA development
github: [bitsabhi]

# Research Papers on Zenodo
custom: ['https://zenodo.org/records/18607789', 'https://zenodo.org/search?q=metadata.creators.person_or_org.name%3A%22Srivastava%2C%20Abhishek%22']
